# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tdct_fib_view_synthesis.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 364)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_milling_angle = QtWidgets.QLabel(Form)
        self.label_milling_angle.setObjectName("label_milling_angle")
        self.gridLayout.addWidget(self.label_milling_angle, 4, 0, 1, 1)
        self.checkBox_save_output = QtWidgets.QCheckBox(Form)
        self.checkBox_save_output.setObjectName("checkBox_save_output")
        self.gridLayout.addWidget(self.checkBox_save_output, 7, 0, 1, 2)
        self.label_zstep = QtWidgets.QLabel(Form)
        self.label_zstep.setObjectName("label_zstep")
        self.gridLayout.addWidget(self.label_zstep, 2, 0, 1, 1)
        self.pushButton_continue = QtWidgets.QPushButton(Form)
        self.pushButton_continue.setObjectName("pushButton_continue")
        self.gridLayout.addWidget(self.pushButton_continue, 8, 0, 1, 2)
        self.doubleSpinBox_pixelsize = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_pixelsize.setDecimals(1)
        self.doubleSpinBox_pixelsize.setMaximum(10000.0)
        self.doubleSpinBox_pixelsize.setObjectName("doubleSpinBox_pixelsize")
        self.gridLayout.addWidget(self.doubleSpinBox_pixelsize, 1, 1, 1, 1)
        self.pushButton_imaging_view = QtWidgets.QPushButton(Form)
        self.pushButton_imaging_view.setObjectName("pushButton_imaging_view")
        self.gridLayout.addWidget(self.pushButton_imaging_view, 5, 0, 1, 1)
        self.pushButton_milling_view = QtWidgets.QPushButton(Form)
        self.pushButton_milling_view.setObjectName("pushButton_milling_view")
        self.gridLayout.addWidget(self.pushButton_milling_view, 5, 1, 1, 1)
        self.doubleSpinBox_rotation_x = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rotation_x.setMinimum(-360.0)
        self.doubleSpinBox_rotation_x.setMaximum(360.0)
        self.doubleSpinBox_rotation_x.setObjectName("doubleSpinBox_rotation_x")
        self.gridLayout.addWidget(self.doubleSpinBox_rotation_x, 3, 1, 1, 1)
        self.label_pixelsize = QtWidgets.QLabel(Form)
        self.label_pixelsize.setObjectName("label_pixelsize")
        self.gridLayout.addWidget(self.label_pixelsize, 1, 0, 1, 1)
        self.lineEdit_filename = QtWidgets.QLineEdit(Form)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.gridLayout.addWidget(self.lineEdit_filename, 6, 1, 1, 1)
        self.label_header = QtWidgets.QLabel(Form)
        self.label_header.setObjectName("label_header")
        self.gridLayout.addWidget(self.label_header, 0, 0, 1, 2)
        self.doubleSpinBox_milling_angle = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_milling_angle.setMaximum(180.0)
        self.doubleSpinBox_milling_angle.setObjectName("doubleSpinBox_milling_angle")
        self.gridLayout.addWidget(self.doubleSpinBox_milling_angle, 4, 1, 1, 1)
        self.label_rotation_x = QtWidgets.QLabel(Form)
        self.label_rotation_x.setObjectName("label_rotation_x")
        self.gridLayout.addWidget(self.label_rotation_x, 3, 0, 1, 1)
        self.label_filename = QtWidgets.QLabel(Form)
        self.label_filename.setObjectName("label_filename")
        self.gridLayout.addWidget(self.label_filename, 6, 0, 1, 1)
        self.doubleSpinBox_zstep = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_zstep.setMaximum(10000.0)
        self.doubleSpinBox_zstep.setObjectName("doubleSpinBox_zstep")
        self.gridLayout.addWidget(self.doubleSpinBox_zstep, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_milling_angle.setText(_translate("Form", "Milling Angle"))
        self.checkBox_save_output.setText(_translate("Form", "Save Output"))
        self.label_zstep.setText(_translate("Form", "Z-Step"))
        self.pushButton_continue.setText(_translate("Form", "Continue"))
        self.pushButton_imaging_view.setText(_translate("Form", "Imaging View"))
        self.pushButton_milling_view.setText(_translate("Form", "Milling View"))
        self.label_pixelsize.setText(_translate("Form", "Pixelsize (x,y)"))
        self.label_header.setText(_translate("Form", "FIB-View Synthesis"))
        self.label_rotation_x.setText(_translate("Form", "Rotation (x-axis)"))
        self.label_filename.setText(_translate("Form", "Filename"))
