# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tdct_fm_import_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 292)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 2)
        self.label_target_step_size = QtWidgets.QLabel(Dialog)
        self.label_target_step_size.setObjectName("label_target_step_size")
        self.gridLayout.addWidget(self.label_target_step_size, 2, 0, 1, 1)
        self.label_description = QtWidgets.QLabel(Dialog)
        self.label_description.setObjectName("label_description")
        self.gridLayout.addWidget(self.label_description, 0, 0, 1, 2)
        self.doubleSpinBox_target_step_size = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_target_step_size.setDecimals(3)
        self.doubleSpinBox_target_step_size.setMaximum(1000.0)
        self.doubleSpinBox_target_step_size.setProperty("value", 1.0)
        self.doubleSpinBox_target_step_size.setObjectName("doubleSpinBox_target_step_size")
        self.gridLayout.addWidget(self.doubleSpinBox_target_step_size, 2, 1, 1, 1)
        self.pushButton_interpolate = QtWidgets.QPushButton(Dialog)
        self.pushButton_interpolate.setObjectName("pushButton_interpolate")
        self.gridLayout.addWidget(self.pushButton_interpolate, 4, 0, 1, 2)
        self.progressBar_interpolation = QtWidgets.QProgressBar(Dialog)
        self.progressBar_interpolation.setProperty("value", 24)
        self.progressBar_interpolation.setObjectName("progressBar_interpolation")
        self.gridLayout.addWidget(self.progressBar_interpolation, 5, 0, 1, 2)
        self.doubleSpinBox_current_step_size = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_current_step_size.setDecimals(3)
        self.doubleSpinBox_current_step_size.setMaximum(1000.0)
        self.doubleSpinBox_current_step_size.setProperty("value", 1.0)
        self.doubleSpinBox_current_step_size.setObjectName("doubleSpinBox_current_step_size")
        self.gridLayout.addWidget(self.doubleSpinBox_current_step_size, 1, 1, 1, 1)
        self.label_error_text = QtWidgets.QLabel(Dialog)
        self.label_error_text.setObjectName("label_error_text")
        self.gridLayout.addWidget(self.label_error_text, 3, 0, 1, 2)
        self.label_current_step_size = QtWidgets.QLabel(Dialog)
        self.label_current_step_size.setObjectName("label_current_step_size")
        self.gridLayout.addWidget(self.label_current_step_size, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_target_step_size.setText(_translate("Dialog", "Target z-step size (nm)"))
        self.label_description.setText(_translate("Dialog", "Filename and Description"))
        self.pushButton_interpolate.setText(_translate("Dialog", "Interpolate"))
        self.label_error_text.setText(_translate("Dialog", "Error Text"))
        self.label_current_step_size.setText(_translate("Dialog", "Current z-step size (nm)"))
